import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Institutional Safety Partnerships — Whaleora', description: 'Safety awareness, education, practical products and resources for campuses, workplaces and communities.' };

const whatsapp = 'https://wa.me/8169219734?text=Hi%20Whaleora!%20I%20would%20like%20to%20explore%20institutional%20partnerships.';

export default function InstitutionsPage() {
  return <main className="page-main institutions-page">
    <section className="institution-hero"><div className="shell"><p className="eyebrow">Institutional partnerships</p><h1>Building a culture<br />of safety, <em>together.</em></h1><div><p>Practical tools, engaging education and reusable resources for communities that want preparedness to become a habit.</p><a href={whatsapp} className="button button-light">Start a conversation <span>↗</span></a></div></div></section>
    <section className="approach shell section-pad"><div><p className="eyebrow dark">Our model</p><h2>Education first.<br /><em>Products second.</em></h2></div><p>Whaleora can help organisations create a joined-up programme: clear awareness, practical learning, thoughtfully chosen tools and resources people can return to.</p></section>
    <section className="model-steps shell"><article><span>01</span><h3>Awareness</h3><p>Clear, relevant conversations about everyday situations.</p></article><article><span>02</span><h3>Education</h3><p>Interactive sessions and practical learning.</p></article><article><span>03</span><h3>Products</h3><p>Everyday tools selected to reinforce preparedness.</p></article><article><span>04</span><h3>Resources</h3><p>Digital and physical material people can revisit.</p></article></section>
    <section className="tracks section-pad"><div className="shell"><p className="eyebrow dark">Partnership tracks</p><div className="track-grid"><article><small>Students & faculty</small><h2>Universities<br />& Campuses</h2><p>Awareness and practical resources designed around campus life.</p><a href={whatsapp}>Enquire on WhatsApp ↗</a></article><article><small>Employee care</small><h2>Corporate<br />Wellness</h2><p>Preparedness as a thoughtful layer of employee wellbeing.</p><a href={whatsapp}>Enquire on WhatsApp ↗</a></article><article><small>Collective action</small><h2>Community<br />Programmes</h2><p>Adaptable initiatives for NGOs, organisations and local communities.</p><a href={whatsapp}>Enquire on WhatsApp ↗</a></article><article><small>Curated commerce</small><h2>Retail &<br />Distribution</h2><p>A considered safety collection for aligned retail environments.</p><a href={whatsapp}>Enquire on WhatsApp ↗</a></article></div></div></section>
    <section className="collaboration shell section-pad"><div><p className="eyebrow dark">How collaboration works</p><h2>A clear path from<br /><em>conversation to support.</em></h2></div><ol><li><span>01</span><div><h3>Understand</h3><p>We begin with your people, context and priorities.</p></div></li><li><span>02</span><div><h3>Design the programme</h3><p>Shape the right blend of awareness, education and tools.</p></div></li><li><span>03</span><div><h3>Deliver</h3><p>Bring the programme to your campus, team or community.</p></div></li><li><span>04</span><div><h3>Support</h3><p>Keep useful resources accessible after the session.</p></div></li></ol></section>
    <section className="institution-cta"><div className="shell"><p>Safer people. Stronger communities.</p><h2>Let’s start a<br /><em>useful conversation.</em></h2><a href={whatsapp} className="button button-light">Talk to Whaleora on WhatsApp →</a><Link href="/contact" className="text-link">Or send an enquiry ↗</Link></div></section>
  </main>;
}
